# Generated by Django 5.1.1 on 2024-09-04 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('nro_apartamento', models.CharField(max_length=4)),
                ('telefono', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
                ('nom_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_vehiculos.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_entrada', models.DateTimeField(verbose_name='fecha y hora de entrada')),
                ('fecha_hora_salida', models.DateTimeField(verbose_name='fecha y hora de salida')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_vehiculos.vehiculo')),
            ],
        ),
    ]
