# Generated by Django 5.1.1 on 2024-09-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
